spring:
  application:
    name: config
  cloud: 
    config:
      server:
        git:
          uri: https://github.com/chencong-plan/springCloud-sell-config-repo.git
          username: chencong-plan
          password: 1042738887cc
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

